version: 0.1.{build}

image: Visual Studio 2017

configuration:
  - release

platform:
  - uwp-x64
  - uwp-x86
#  - uwp-arm64
#  - uwp-arm
#  - desktop-x64
#  - desktop-x86
#  - desktop-arm64
  - nuget

for:
-
  matrix:
    except:
      - platform: nuget

#  init:
#    - ps: $env:Path="C:\msys64\usr\bin;"+$env:Path

#  before_build:
#    - ps: git submodule update -q --init --recursive

  build_script:
#    - bash -c "./build.sh %PLATFORM%
    - ps: echo "Building $env:platform"

  after_build:
#    - ps: Compress-Archive -Path ".\Build\$env:platform\*" -DestinationPath ".\ffmpeg_$env:platform.zip"

  artifacts:
#    - path: '**\*.zip'

-
  matrix:
    only:
      - platform: nuget

  build_script:
  - ps: echo "Building nuuuuuget"

  artifacts:
    - path: '**\*.nuget'