version: 0.1.{build}

image: Visual Studio 2017

configuration:
  - release

platform:
  - uwp_x64
#  - uwp_x86
#  - uwp_arm64
#  - uwp_arm
#  - desktop_x64
#  - desktop_x86
#  - desktop_arm64

init:
  - ps: $env:Path+=";C:\msys64\usr\bin"

build_script:
  - ps: bash -c "./build.sh $env:platform"

artifacts:
  - path: '**\%target_name%*.dll'
  - path: '**\%target_name%*.lib'
  - path: '**\%target_name%*.pdb'
  - path: '**\libretro.h'