version: 0.1.{build}

image: Visual Studio 2017

configuration:
  - release

platform:
  - uwp-x64
#  - uwp-x86
#  - uwp-arm64
#  - uwp-arm
#  - desktop-x64
#  - desktop-x86
#  - desktop-arm64

init:
  - ps: $env:Path+=";C:\msys64\usr\bin"

build_script:
  - ps: bash -c "./build.sh $env:platform"

artifacts:
  - path: '**\%target_name%*.dll'
  - path: '**\%target_name%*.lib'
  - path: '**\%target_name%*.pdb'
  - path: '**\libretro.h'