version: 0.1.{build}

image: Visual Studio 2017

configuration:
  - release

platform:
  - uwp-x64
#  - uwp-x86
#  - uwp-arm64
#  - uwp-arm
#  - desktop-x64
#  - desktop-x86
#  - desktop-arm64

init:
  - ps: $env:Path+=";C:\msys64\usr\bin"

before_build:
  - ps: git submodule update

build_script:
  - ps: bash -c "./build.sh $env:platform"

artifacts:
  - path: '**\*.zip'